# Generated by Django 5.0.6 on 2024-08-27 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_bio_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaders',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constituency'),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.county'),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ward'),
        ),
    ]
