# Generated by Django 5.1 on 2024-09-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_leaders_constituency_alter_leaders_county_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='content',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vedio',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
