# Generated by Django 5.1 on 2024-09-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_content_text_text_alter_image_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vedio',
            new_name='Video',
        ),
    ]
