# Generated by Django 5.1 on 2024-09-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_vedio_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaders',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
